# šis file yra skirtas deklaruoti, kas bus sistemoje.

lab50: #deklaruoja, kas bus reikalinga lab50 aplinkoje
  files:
    - !exclude "*" #šitas visada reikalingas.
    - !include "balsavimas.cpp" #balsavimas.cpp reikia pakeisti į jūsų uždavinio pavadinimą.cpp.
    - !include "U1.txt" # duomenų failo pavadinimas.
    - !include "U1rez.txt" # rezultatų failo pavadinimas.
    
check50:
  files:
    - !exclude "*" # šitas visada reikalingas.
    - !require "balsavimas.cpp" #balsavimas.cpp reikia pakeisti į jūsų uždavinio pavadinimą.cpp.
    - !require "U1.txt" # duomenų failo pavadinimas.
    - !require "U1rez.txt" # rezultatų failo pavadinimas.
